name: Advanced SBOM Dashboard
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM
  workflow_dispatch:

jobs:
  sbom-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download SBOMs from multiple sources
        run: |
          # Create directory for SBOM files
          mkdir -p sboms
          
          # Download SBOMs from different sources
          # Example: Download from artifact storage, other repositories, etc.
          # curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          #   -o sboms/frontend.cyclonedx.json \
          #   https://api.github.com/repos/yourorg/frontend/contents/sbom.cyclonedx.json
          
          # For this example, we'll create sample SBOM files
          echo '{
            "bomFormat": "CycloneDX",
            "specVersion": "1.4",
            "version": 1,
            "metadata": {
              "timestamp": "2024-01-01T00:00:00Z",
              "tools": [{"vendor": "syft", "name": "syft", "version": "1.0.0"}]
            },
            "components": [
              {
                "type": "library",
                "name": "react",
                "version": "18.2.0",
                "purl": "pkg:npm/react@18.2.0",
                "licenses": [{"license": {"id": "MIT"}}]
              }
            ],
            "vulnerabilities": [
              {
                "id": "CVE-2024-12345",
                "description": "High severity vulnerability in react",
                "ratings": [{"score": 8.5, "severity": "high", "method": "CVSSv3"}],
                "affects": [{"ref": "pkg:npm/react@18.2.0"}]
              }
            ]
          }' > sboms/frontend.cyclonedx.json
          
          echo '{
            "bomFormat": "CycloneDX",
            "specVersion": "1.4",
            "version": 1,
            "metadata": {
              "timestamp": "2024-01-01T00:00:00Z",
              "tools": [{"vendor": "syft", "name": "syft", "version": "1.0.0"}]
            },
            "components": [
              {
                "type": "library",
                "name": "express",
                "version": "4.18.2",
                "purl": "pkg:npm/express@4.18.2",
                "licenses": [{"license": {"id": "MIT"}}]
              }
            ],
            "vulnerabilities": [
              {
                "id": "CVE-2024-12346",
                "description": "Medium severity vulnerability in express",
                "ratings": [{"score": 5.5, "severity": "medium", "method": "CVSSv3"}],
                "affects": [{"ref": "pkg:npm/express@4.18.2"}]
              }
            ]
          }' > sboms/backend.cyclonedx.json
      
      - name: Generate Comprehensive SBOM Dashboard
        uses: sidbhasin13/sbom-ui-action@v1
        with:
          sbom-files: 'sboms/**/*.cyclonedx.json'
          output-dir: 'sbom-dashboard'
          title: 'Multi-Component SBOM Dashboard'
          theme: 'dark'
